apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env
data:
  .env: |
    APP_NAME=Laravel
    APP_ENV=production
    APP_KEY=base64:someKeyHere==
    APP_DEBUG=false
    APP_URL=https://escanor.example.com
