name: Build and Deploy to K8s

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Set up QEMU (for cross-platform builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64

  deploy:
    runs-on: [self-hosted, linux, arm64]
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install kubectl
        run: |
          curl -LO https://dl.k8s.io/release/v1.30.0/bin/linux/arm64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Set KUBECONFIG and deploy
        run: |
          echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kubeconfig.yaml
          export KUBECONFIG=$PWD/kubeconfig.yaml
          NAMESPACE=client-${{ github.actor }}
          kubectl get namespace $NAMESPACE || kubectl create namespace $NAMESPACE
          kubectl apply -n $NAMESPACE -f deployment.yaml
          kubectl rollout status -n $NAMESPACE deployment nginx-deployment

      - name: Install Python & pytest
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install pytest requests

      - name: Run dynamic tests (auto-detect language)
        run: |
          if [ -f tests/test_laravel.py ]; then pytest tests/test_laravel.py; \
          elif [ -f tests/test_app.py ]; then pytest tests/test_app.py; \
          else echo "No tests found"; fi

      - name: Add GitHub Status Badge (if needed)
        run: echo "![Build Status](https://github.com/${{ github.repository }}/actions/workflows/deploy.yml/badge.svg)" > status-badge.md

      - name: Cleanup (optional)
        run: rm -f kubeconfig.yaml

